### ISSUE TITLE
Issues Running main.py

### ISSUE THREAD

**Issue by MarjorieRWillner** [kobybibas/test_tube_classification#1]
Hi Koby,

Your code looks really useful but when I try to run main.py I get some errors when the calls to TestTubesClass.py are made. 

The error I couldn't fix is a type error, shown in the attached

![Capture](https://user-images.githubusercontent.com/26447902/64560100-dacaab80-d315-11e9-941c-14625f351691.PNG)

do you have any suggestions?

**Comment by kobybibas** [comment]
Hi,
I change the default dtype to float.
Please pull and try again
